#!/usr/bin/env python3

import socket
import random
import sys

sys.path.append(sys.path[0] + "/..")

from src import constants as Constants
from src import util

_seq = 0
_session_id = random.randint(1, 100)


# https://stackoverflow.com/questions/3393612/run-certain-code-every-n-seconds
def test_send(hostname: str, portnum: int):
    global _seq

    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    exclude_set = {"ALIVE"}

    for cur_enum in Constants.Command:
        if (cur_enum.name in exclude_set):
            continue
        msg = "something here" if cur_enum == Constants.Command.DATA else None
        data_msg = util.pack(cur_enum.value, _seq, _session_id, msg)
        s.sendto(data_msg, (hostname, portnum))
        _seq += 1


if __name__ == "__main__":
    print("Client Starting")
    hostname = sys.argv[1]
    portnum = int(sys.argv[2])
    test_send(hostname, portnum)
